--(A)
SELECT EMPLOYEES.LAST_NAME, EMPLOYEES.SALARY, JOBS.JOB_TITLE
FROM EMPLOYEES JOIN JOBS USING (JOB_ID);

--(B)
SELECT DEPARTMENTS.DEPARTMENT_NAME, COUNTRIES.COUNTRY_NAME
FROM DEPARTMENTS JOIN LOCATIONS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID);

--(C)
SELECT COUNTRIES.COUNTRY_ID, COUNTRIES.COUNTRY_NAME, COUNT(DEPARTMENTS.DEPARTMENT_ID) AS DEPARTMENT_COUNT
FROM COUNTRIES LEFT JOIN LOCATIONS ON(COUNTRIES.COUNTRY_ID=LOCATIONS.COUNTRY_ID) LEFT JOIN DEPARTMENTS ON(LOCATIONS.LOCATION_ID=DEPARTMENTS.LOCATION_ID)
GROUP BY COUNTRIES.COUNTRY_ID, COUNTRIES.COUNTRY_NAME;

--(D)
SELECT E.EMPLOYEE_ID , COUNT(J.EMPLOYEE_ID) AS SWITCHED_JOBS
FROM EMPLOYEES E LEFT JOIN JOB_HISTORY J ON(E.EMPLOYEE_ID=J.EMPLOYEE_ID)
GROUP BY E.EMPLOYEE_ID
ORDER BY SWITCHED_JOBS DESC;

--(E)
SELECT D.DEPARTMENT_NAME, J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E ON (D.DEPARTMENT_ID=E.DEPARTMENT_ID) RIGHT JOIN JOBS J ON (J.JOB_ID=E.JOB_ID)
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, J.JOB_ID, J.JOB_TITLE;

--(F)
SELECT E1.LAST_NAME, COUNT(E2.EMPLOYEE_ID) EMPLOYEE_COUNT
FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON (E1.HIRE_DATE>E2.HIRE_DATE)
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
ORDER BY EMPLOYEE_COUNT ASC;

--(G)
--CAN'T SOLVE JUST BY JOINING.

--(H)
SELECT E1.EMPLOYEE_ID, COUNT(E2.EMPLOYEE_ID) AS LOW_SALARY_EMPLOYEE
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON(E1.SALARY>E2.SALARY)
GROUP BY E1.EMPLOYEE_ID
HAVING COUNT(E2.EMPLOYEE_ID)>=3
ORDER BY LOW_SALARY_EMPLOYEE DESC;

--(I)
SELECT E1.EMPLOYEE_ID, COUNT(DISTINCT E2.SALARY) AS RANK 
FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON (E1.SALARY<=E2.SALARY)
GROUP BY E1.EMPLOYEE_ID
ORDER BY RANK ASC;

--(J)
SELECT E1.EMPLOYEE_ID,(E1.FIRST_NAME ||' '||E1.LAST_NAME) AS FULL_NAME, E1.SALARY
FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON (E1.SALARY<E2.SALARY)
GROUP BY E1.EMPLOYEE_ID,(E1.FIRST_NAME ||' '||E1.LAST_NAME), E1.SALARY
HAVING COUNT(E2.EMPLOYEE_ID)<3
ORDER BY E1.SALARY DESC;





