--(a)
--INCASE OF USING HAVING YOU CANNOT USE ALIAS THUS THE FOLLOWING WILL BE INVALID.....
-- HAVING AVERAGE_SALARY>5000;
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) AS AVERAGE_SALARY FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>5000;
ORDER BY AVERAGE_SALARY ASC;
