--(a)
-- SELECT FLOOR(SALARY/5000) SALARY_RANGE, COUNT(*) EMPLOYEE_COUNT FROM EMPLOYEES
-- GROUP BY FLOOR(SALARY/5000) ;

--(b)
SELECT TO_CHAR(HIRE_DATE,'YYYY') HIRE_YEAR, JOB_ID, COUNT(*) EMPLOYEE_HIRED FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'YYYY'), JOB_ID
ORDER BY HIRE_YEAR ASC;