--(A)
SELECT E1.LAST_NAME, E1.SALARY FROM EMPLOYEES E1
WHERE (
    SELECT COUNT(*) FROM EMPLOYEES E2
    WHERE E2.SALARY<E1.SALARY
)>=3;

--(B)
SELECT (SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID=E.DEPARTMENT_ID) AS DEPARTMENT
FROM EMPLOYEES E
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>(
SELECT MIN(SALARY) FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID<>E.DEPARTMENT_ID
);

--(C)
SELECT (
SELECT D.DEPARTMENT_NAME FROM DEPARTMENTS D
WHERE D.DEPARTMENT_ID=E.DEPARTMENT_ID
) AS HIGHEST_EPLOYEE_DEPT
FROM EMPLOYEES E
GROUP BY E.DEPARTMENT_ID
HAVING COUNT(*)>= ALL (
SELECT COUNT(*) FROM EMPLOYEES E2
GROUP BY E2.DEPARTMENT_ID
);

--(D)
SELECT (SELECT E.LAST_NAME FROM EMPLOYEES E WHERE E.EMPLOYEE_ID=J1.EMPLOYEE_ID)
FROM JOB_HISTORY J1
WHERE (
SELECT COUNT(*) FROM JOB_HISTORY J2
WHERE J2.JOB_ID=J1.JOB_ID
GROUP BY J2.JOB_ID
)>1;

--(E)
SELECT E.LAST_NAME, E.SALARY, D.MINSAL, D.MAXSAL 
FROM EMPLOYEES E, (
SELECT DEPARTMENT_ID, MAX(SALARY) AS MAXSAL, MIN(SALARY) AS MINSAL 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
) D 
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--(F) 
SELECT (SELECT J.JOB_TITLE FROM JOBS J WHERE J.JOB_ID=E.JOB_ID) AS JOB_TITLE,
E.LAST_NAME, E.SALARY
FROM EMPLOYEES E
WHERE E.SALARY=(
SELECT MAX(SALARY) FROM EMPLOYEES E2
WHERE E2.JOB_ID=E.JOB_ID
GROUP BY E2.JOB_ID
);






















