--(a)
-- SELECT (FIRST_NAME||' '||LAST_NAME) AS NAME, HIRE_DATE FROM EMPLOYEES
-- WHERE HIRE_DATE < '01-JAN-2010';

--(b)
-- SELECT * FROM LOCATIONS
-- WHERE COUNTRY_ID IN ('CA','DE','UK');

--(c)
-- SELECT FIRST_NAME, COMMISSION_PCT FROM EMPLOYEES
-- WHERE COMMISSION_PCT IS NULL;

--(d)
-- SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
-- WHERE LAST_NAME LIKE 'A%';

--(e)
-- SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
-- WHERE LAST_NAME LIKE 'S%n'; 

--(f)
-- SELECT DEPARTMENT_NAME, MANAGER_ID FROM DEPARTMENTS 
-- WHERE MANAGER_ID = 100;

--(g)
-- SELECT * FROM EMPLOYEES WHERE JOB_ID ='AD_PRES' AND SALARY>=23000;

--(h)
-- SELECT LAST_NAME FROM EMPLOYEES
-- WHERE LAST_NAME NOT LIKE '%s';

--(i)
-- SELECT LAST_NAME, COMMISSION_PCT FROM EMPLOYEES
-- WHERE COMMISSION_PCT<=0.3 OR  COMMISSION_PCT IS NULL;

--(j)
-- SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
-- WHERE HIRE_DATE > '01-JAN-2005';

--(k)
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-2005' AND '31-JAN-2005'--(THE DATES ARE INCLUSIVE)












