--(A)
SELECT
  LAST_NAME,
  DEPARTMENT_ID
FROM
  EMPLOYEES
WHERE
  DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES');
  
  --(B)
SELECT
  LAST_NAME,
  SALARY
FROM
  EMPLOYEES
WHERE
  SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES'));
  
  --(C)
SELECT
  LAST_NAME,
  SALARY
FROM
  EMPLOYEES
WHERE
  SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES'));
  
  --(D)
SELECT
  LAST_NAME,
  SALARY
FROM
  EMPLOYEES
WHERE
  SALARY BETWEEN (SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES')) - 5000
  AND (SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES')) + 5000;
  
  
  