--(a)
SELECT (FIRST_NAME||' '||LAST_NAME) AS NAME , SALARY, COMMISSION_PCT FROM EMPLOYEES
ORDER BY NVL(COMMISSION_PCT,0) ASC, SALARY DESC;

--(b)
SELECT COUNTRY_NAME FROM COUNTRIES
ORDER BY COUNTRY_NAME ASC;