--(a)
-- SELECT UPPER((SUBSTR(COUNTRY_NAME,1,3)||'_'||SUBSTR(COUNTRY_NAME,-3,3))) AS COUNTRY_CODE FROM COUNTRIES;

--(b)
SELECT LPAD((FIRST_NAME||' '||LAST_NAME), 60,'*')) FROM EMPLOYEES;

--(c)
SELECT JOB_TITLE  FROM JOBS 
WHERE UPPER(JOB_TITLE) LIKE '%MANAGER%';