--(A)
SELECT DEPARTMENT_ID, 
SUM(CASE WHEN SALARY>=15000 THEN 1 ELSE 0 END) AS "A+",
SUM(CASE WHEN SALARY>=10000 AND SALARY<15000 THEN 1 ELSE 0 END) AS "A",
SUM(CASE WHEN SALARY>=5000 AND SALARY<10000 THEN 1 ELSE 0 END) AS "B",
SUM(CASE WHEN SALARY<5000 THEN 1 ELSE 0 END) AS "C"

FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

--(A)
SELECT E1.DEPARTMENT_ID,
NVL(
(
  SELECT COUNT(*) FROM EMPLOYEES E2
  WHERE E2.DEPARTMENT_ID=E1.DEPARTMENT_ID AND E2.SALARY>=15000
  GROUP BY E2.DEPARTMENT_ID
),0) AS "A+",
NVL(
(
  SELECT COUNT(*) FROM EMPLOYEES E2
  WHERE E2.DEPARTMENT_ID=E1.DEPARTMENT_ID AND E2.SALARY>=10000 AND E2.SALARY<15000
  GROUP BY E2.DEPARTMENT_ID
),0) AS "A",
NVL(
(
  SELECT COUNT(*) FROM EMPLOYEES E2
  WHERE E2.DEPARTMENT_ID=E1.DEPARTMENT_ID AND E2.SALARY>=5000 AND E2.SALARY<10000
  GROUP BY E2.DEPARTMENT_ID
),0) AS "B",
NVL(
(
  SELECT COUNT(*) FROM EMPLOYEES E2
  WHERE E2.DEPARTMENT_ID=E1.DEPARTMENT_ID AND E2.SALARY<5000
  GROUP BY E2.DEPARTMENT_ID
),0) AS "C"
FROM EMPLOYEES E1
GROUP BY E1.DEPARTMENT_ID;

--(B)
SELECT DEPARTMENT_ID,
SUM(DECODE(FLOOR(SALARY/15000),0,0,1)) AS "A+",
SUM(DECODE(FLOOR(SALARY/5000),2,1,0)) AS "A",
SUM(DECODE(FLOOR(SALARY/5000),1,1,0)) AS "B",
SUM(DECODE(FLOOR(SALARY/5000),0,1,0)) AS "C"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--(C)
SELECT E1.EMPLOYEE_ID, E2.EMPLOYEE_COUNT, E3.EMPLOYEE_COUNT
FROM EMPLOYEES E1, (
SELECT E2.DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES E2
GROUP BY E2.DEPARTMENT_ID
) E2, (
SELECT E2.DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES E2
GROUP BY E2.DEPARTMENT_ID
) E3
WHERE E1.DEPARTMENT_ID=E2.DEPARTMENT_ID AND E3.DEPARTMENT_ID=(
SELECT D.DEPARTMENT_ID FROM DEPARTMENTS D
WHERE D.MANAGER_ID=E1.MANAGER_ID
);


