--(a)
SELECT MANAGER_ID, COUNT (*) AS EMPLOYEE_COUNT FROM EMPLOYEES
GROUP BY MANAGER_ID;

--(b)
SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT FROM EMPLOYEES
WHERE SALARY>3000 
GROUP BY DEPARTMENT_ID;

--(c)
SELECT DEPARTMENT_ID, MIN(SALARY) AS MINIMUM_SALARY, MAX(SALARY) AS MAXIMUM_SALARY, ROUND(AVG(SALARY),2) AS AVERAGE_SALARY FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY AVERAGE_SALARY DESC, MAXIMUM_SALARY DESC, MINIMUM_SALARY DESC;

-- If you write 'Order by smthng' without specifying asc or desc then by default it will be treated as asc;











