--1.
SELECT EMPLOYEE_ID, (FIRST_NAME||' '||LAST_NAME) AS "FULL NAME", DEPARTMENT_ID, SALARY*(1+NVL(COMMISSION_PCT,0)) AS "MONTHLY SALARY" FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%' AND SUBSTR(LAST_NAME, 4, 1) = 'n' AND DEPARTMENT_ID BETWEEN 20 AND 70;

--2.
SELECT JOB_ID FROM JOB_HISTORY
WHERE END_DATE-START_DATE<=1500
GROUP BY JOB_ID
HAVING COUNT(*)>=2;

--3.
SELECT DEPARTMENT_ID, MAX(SALARY) AS MAXIMUM_SALARY, MIN(SALARY) AS MINIMUM_SALARY, ROUND(AVG(SALARY),4) AS AVERAGE_SALARY FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID <>50
ORDER BY MAXIMUM_SALARY-MINIMUM_SALARY DESC, AVERAGE_SALARY ASC;

--4.
SELECT MANAGER_ID, COUNT(*) AS MANAGED_EMPLOYEE, ROUND(AVG(SALARY),4) AS AVERAGE_SALARY FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MANAGER_ID IS NOT NULL AND COUNT(*) < 10 AND AVG(SALARY) < 4000
ORDER BY MANAGED_EMPLOYEE ASC, AVERAGE_SALARY DESC;

--5.
SELECT LAST_NAME  FROM EMPLOYEES
WHERE MOD(LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(LAST_NAME),'A',''),'E',''),'I',''),'O',''),'U','')),2)=1;