
--1
-- SELECT COUNTRY_ID, COUNT(DISTINCT CITY) AS CITY_COUNT, COUNT(DISTINCT STATE_PROVINCE) AS PROVINCE_COUNT FROM LOCATIONS
-- GROUP BY COUNTRY_ID
-- HAVING COUNT(DISTINCT STATE_PROVINCE)>0 AND COUNT(DISTINCT CITY)>=2;

--2
-- SELECT DEPARTMENT_ID FROM JOB_HISTORY
-- WHERE END_DATE-START_DATE<=600
-- GROUP BY DEPARTMENT_ID
-- HAVING COUNT(*)<=1;

--3
-- SELECT DEPARTMENT_ID, MAX(HIRE_DATE) MAX_HIRE, MIN(HIRE_DATE) MIN_HIRE,(MAX(HIRE_DATE)-MIN(HIRE_DATE)), ROUND(AVG(SALARY),2) AS AVERAGE_SALARY FROM EMPLOYEES
-- GROUP BY DEPARTMENT_ID
-- HAVING DEPARTMENT_ID IS NOT NULL
-- ORDER BY MAX_HIRE-MIN_HIRE ASC, AVERAGE_SALARY DESC;

--4
-- SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME,COMMISSION_PCT, SALARY*12 AS ANNUAL_SALARY, SALARY AS MONTHLY_SALARY, SALARY+(SALARY*12)*NVL(COMMISSION_PCT,-0.05)*0.01 FROM EMPLOYEES;

--5
-- SELECT MANAGER_ID,COUNT(*) AS MANAGED_EMPLOYEES, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES
-- WHERE TO_CHAR(HIRE_DATE,'MM') IN ('03','09','12') AND MANAGER_ID IS NOT NULL
-- GROUP BY MANAGER_ID
-- HAVING TRUNC(AVG(SALARY),0)-AVG(SALARY)=0
-- ORDER BY MANAGED_EMPLOYEES ASC, AVERAGE_SALARY DESC;









